src/main/java/br/com/historia/historiacolaborativa/domain/Promocao.java
package br.com.historia.historiacolaborativa.domain;

import static javax.persistence.GenerationType.SEQUENCE;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

@Entity
public class Promocao implements Serializable {

	private static final long serialVersionUID = 1L;
	
	/*
	 *  If you are using Glassfish then remove the strategy attribute
	 */
	@Id
	@GeneratedValue(strategy = SEQUENCE)
	private Long id_promocao;
	
	@Column
	private String descricao;
	
	
	
	public Promocao() {
		super();
	}
	
	public Promocao(String descricao) {
		this.descricao = descricao;
		
	}
	
	public Long getId_promocao() {
		return this.id_promocao;
	}
	
	public void setId_promocao(Long id) {
		this.id_promocao = id;
	}
	
	public String getDescription() {
		return this.descricao;
	}
	
	public void setDescription(String descricao) {
		this.descricao = descricao;
	}
	
}

src/main/java/br/com/historia/historiacolaborativa/view/BookmarkEditMB.java
package br.com.historia.historiacolaborativa.view;

import javax.inject.Inject;

import br.gov.frameworkdemoiselle.annotation.PreviousView;
import br.gov.frameworkdemoiselle.stereotype.ViewController;
import br.gov.frameworkdemoiselle.template.AbstractEditPageBean;
import br.gov.frameworkdemoiselle.transaction.Transactional;

import br.com.historia.historiacolaborativa.business.BookmarkBC;
import br.com.historia.historiacolaborativa.domain.Bookmark;

@ViewController
@PreviousView("/bookmark_list.xhtml")
public class BookmarkEditMB extends AbstractEditPageBean<Bookmark, Long> {

	private static final long serialVersionUID = 1L;

	@Inject
	private BookmarkBC bookmarkBC;

	@Override
	@Transactional
	public String delete() {
		this.bookmarkBC.delete(getId());
		return getPreviousView();
	}

	@Override
	@Transactional
	public String insert() {
		this.bookmarkBC.insert(getBean());
		return getPreviousView();
	}

	@Override
	@Transactional
	public String update() {
		this.bookmarkBC.update(getBean());
		return getPreviousView();
	}

	@Override
	protected Bookmark handleLoad(Long id) {
		return this.bookmarkBC.load(id);
	}
}

src/main/java/br/com/historia/historiacolaborativa/view/BookmarkListMB.java
package br.com.historia.historiacolaborativa.view;

import java.util.Iterator;
import java.util.List;

import javax.inject.Inject;

import br.gov.frameworkdemoiselle.annotation.NextView;
import br.gov.frameworkdemoiselle.annotation.PreviousView;
import br.gov.frameworkdemoiselle.stereotype.ViewController;
import br.gov.frameworkdemoiselle.template.AbstractListPageBean;
import br.gov.frameworkdemoiselle.transaction.Transactional;

import br.com.historia.historiacolaborativa.business.BookmarkBC;
import br.com.historia.historiacolaborativa.domain.Bookmark;

@ViewController
@NextView("/bookmark_edit.xhtml")
@PreviousView("/bookmark_list.xhtml")
public class BookmarkListMB extends AbstractListPageBean<Bookmark, Long> {

	private static final long serialVersionUID = 1L;

	@Inject
	private BookmarkBC bc;

	@Override
	protected List<Bookmark> handleResultList() {
		return this.bc.findAll();
	}

	@Transactional
	public String deleteSelection() {
		boolean delete;
		for (Iterator<Long> iter = getSelection().keySet().iterator(); iter.hasNext();) {
			Long id = iter.next();
			delete = getSelection().get(id);

			if (delete) {
				bc.delete(id);
				iter.remove();
			}
		}
		return getPreviousView();
	}

}

src/main/java/br/com/historia/historiacolaborativa/view/EstabelecimentoEditMB.java
package br.com.historia.historiacolaborativa.view;

import javax.inject.Inject;
import br.gov.frameworkdemoiselle.annotation.PreviousView;
import br.gov.frameworkdemoiselle.stereotype.ViewController;
import br.gov.frameworkdemoiselle.template.AbstractEditPageBean;
import br.gov.frameworkdemoiselle.transaction.Transactional;
import br.com.historia.historiacolaborativa.business.*;
import br.com.historia.historiacolaborativa.domain.*;
import javax.faces.model.*;
import org.primefaces.event.TransferEvent;
import org.primefaces.model.DualListModel;
import java.util.*;

// To remove unused imports press: Ctrl+Shift+o

@ViewController
@PreviousView("./estabelecimento_list.jsf")
public class EstabelecimentoEditMB extends AbstractEditPageBean<Estabelecimento, Integer> {

	private static final long serialVersionUID = 1L;

	@Inject
	private EstabelecimentoBC estabelecimentoBC;
	

	
	@Override
	@Transactional
	public String delete() {
		this.estabelecimentoBC.delete(getId());
		return getPreviousView();
	}
	
	@Override
	@Transactional
	public String insert() {
		this.estabelecimentoBC.insert(this.getBean());
		return getPreviousView();
	}
	
	@Override
	@Transactional
	public String update() {
		this.estabelecimentoBC.update(this.getBean());
		return getPreviousView();
	}
	
	@Override
	protected Estabelecimento handleLoad(Integer id) {
		return this.estabelecimentoBC.load(id);
	}	
}

src/main/java/br/com/historia/historiacolaborativa/view/EstabelecimentoListMB.java
package br.com.historia.historiacolaborativa.view;

import java.util.Iterator;
import java.util.List;
import javax.inject.Inject;
import br.gov.frameworkdemoiselle.annotation.NextView;
import br.gov.frameworkdemoiselle.annotation.PreviousView;
import br.gov.frameworkdemoiselle.stereotype.ViewController;
import br.gov.frameworkdemoiselle.template.AbstractListPageBean;
import br.gov.frameworkdemoiselle.transaction.Transactional;
import br.com.historia.historiacolaborativa.business.EstabelecimentoBC;
import br.com.historia.historiacolaborativa.domain.Estabelecimento;

@ViewController
@NextView("./estabelecimento_edit.jsf")
@PreviousView("./estabelecimento_list.jsf")
public class EstabelecimentoListMB extends AbstractListPageBean<Estabelecimento, Integer> {

	private static final long serialVersionUID = 1L;

	@Inject
	private EstabelecimentoBC estabelecimentoBC;
	
	@Override
	protected List<Estabelecimento> handleResultList() {
		return this.estabelecimentoBC.findAll();
	}
	
	@Transactional
	public String deleteSelection() {
		boolean delete;
		for (Iterator<Integer> iter = getSelection().keySet().iterator(); iter.hasNext();) {
			Integer id = iter.next();
			delete = getSelection().get(id);
			if (delete) {
				estabelecimentoBC.delete(id);
				iter.remove();
			}
		}
		return getPreviousView();
	}

}

src/main/java/br/com/historia/historiacolaborativa/view/FileUploadMB.java
package br.com.historia.historiacolaborativa.view;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean; 
import javax.faces.bean.RequestScoped; 
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletResponse;

import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.UploadedFile;
@ManagedBean(name="fileUploadMB") 
@RequestScoped 
public class FileUploadMB {
	public FileUploadMB() {
		
	} 
	
	public void doUpload(FileUploadEvent fileUploadEvent) { 
		UploadedFile uploadedFile = fileUploadEvent.getFile(); 
		String fileNameUploaded = uploadedFile.getFileName(); 
		long fileSizeUploaded = uploadedFile.getSize(); 
		String infoAboutFile = "<br/> Arquivo recebido: <b>" +fileNameUploaded +"</b><br/>"+ "Tamanho do Arquivo: <b>"+fileSizeUploaded+"</b>"; 
		FacesContext facesContext = FacesContext.getCurrentInstance(); 
		facesContext.addMessage(null, new FacesMessage("Sucesso", infoAboutFile)); 
		} 
	
	
	
	public void fileUploadAction(FileUploadEvent event) { 
		try { 
			FacesContext facesContext = FacesContext.getCurrentInstance(); 
	    	facesContext.addMessage(null, new FacesMessage("Sucesso", "PASSOU")); 		
	    	//ExternalContext externalContext = FacesContext.getCurrentInstance().getExternalContext(); 
		//HttpServletResponse response = (HttpServletResponse) externalContext.getResponse(); 

		FacesContext aFacesContext = FacesContext.getCurrentInstance(); 
		ServletContext context = (ServletContext) aFacesContext.getExternalContext().getContext(); 

		String realPath = context.getRealPath("/"); 

		// Aqui cria o diretorio cash não exista 
		File file = new File("./fotos/"); 
		file.mkdirs(); 

		byte[] arquivo = event.getFile().getContents(); 
		String caminho = "/images/" + event.getFile().getFileName(); 

		// esse trecho grava o arquivo no diretório 
		FileOutputStream fos = new FileOutputStream(caminho); 
		fos.write(arquivo); 
		fos.close(); 


		} catch (Exception ex) { 
		System.out.println("Erro no upload de imagem" + ex); 
		} 
	}
	
	public void teste(FileUploadEvent event) throws IOException{
		UploadedFile file = event.getFile();
		byte[] arquivo = file.getContents();
		String nome = file.getFileName();
		String caminho = "./imagens/" + nome;
		FileOutputStream fos = new FileOutputStream(caminho); 
		fos.write(arquivo);
		fos.close();
		
	}
	
	public void carregarArquivo(FileUploadEvent event) // metodo chamado quando o arquivo acaba de carregar no serverSide  
            throws FileNotFoundException, IOException {  
          System.out.println("TESTE");
        FacesMessage msg = new FacesMessage("Sucesso "+event.getFile().getFileName()+" foi carregado.", event.getFile()  
                .getFileName() + " foi carregado."); // mensagem pra saber se ouve sucesso  
          
          
       String arquivo = event.getFile().getFileName(); // pego o nome do arquivo  
          
          
          
          
          
        String caminho = FacesContext.getCurrentInstance().getExternalContext()  
                .getRealPath("./imagens/"+arquivo ); // diretorio o qual vou salvar o arquivo do upload, equivale ao nome completamente qualificado  
          
          
  
  
        byte[] conteudo = event.getFile().getContents();  // daqui pra baixo é somente operações de IO.  
        FileOutputStream fos = new FileOutputStream(caminho);  
        fos.write(conteudo);  
        fos.close();  
          
          
          
          
  
    }

	}


src/main/java/br/com/historia/historiacolaborativa/view/ImagesViewMB.java
package br.com.historia.historiacolaborativa.view;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
 
@ManagedBean
public class ImagesViewMB {
     
    private List<String> images;
     
    @PostConstruct
    public void init() {
        images = new ArrayList<String>();
        for (int i = 1; i <= 2; i++) {
            images.add("point" + i + ".jpg");
            System.out.println("PASSOU AQUI!!!!!");
        }
        images.add("point1.jpg");
        images.add("point2.jpg");
    }
    
    
    public ImagesViewMB(){
    	images = new ArrayList<String>();
        images.add("point.jpg");
        images.add("point.jpg");
        System.out.println("PASSOU AQUI!!!!!");

    }
    
    
    
 
    public List<String> getImages() {
        return images;
    }
}

src/main/java/br/com/historia/historiacolaborativa/view/PromocaoEditMB.java
package br.com.historia.historiacolaborativa.view;

import javax.inject.Inject;
import br.gov.frameworkdemoiselle.annotation.PreviousView;
import br.gov.frameworkdemoiselle.stereotype.ViewController;
import br.gov.frameworkdemoiselle.template.AbstractEditPageBean;
import br.gov.frameworkdemoiselle.transaction.Transactional;
import br.com.historia.historiacolaborativa.business.*;
import br.com.historia.historiacolaborativa.domain.*;
import javax.faces.model.*;
import org.primefaces.event.TransferEvent;
import org.primefaces.model.DualListModel;
import java.util.*;

// To remove unused imports press: Ctrl+Shift+o

@ViewController
@PreviousView("./promocao_list.jsf")
public class PromocaoEditMB extends AbstractEditPageBean<Promocao, Long> {

	private static final long serialVersionUID = 1L;

	@Inject
	private PromocaoBC promocaoBC;
	

	
	@Override
	@Transactional
	public String delete() {
		this.promocaoBC.delete(getId());
		return getPreviousView();
	}
	
	@Override
	@Transactional
	public String insert() {
		this.promocaoBC.insert(this.getBean());
		return getPreviousView();
	}
	
	@Override
	@Transactional
	public String update() {
		this.promocaoBC.update(this.getBean());
		return getPreviousView();
	}
	
	@Override
	protected Promocao handleLoad(Long id) {
		return this.promocaoBC.load(id);
	}	
}

src/main/java/br/com/historia/historiacolaborativa/view/PromocaoListMB.java
package br.com.historia.historiacolaborativa.view;

import java.util.Iterator;
import java.util.List;
import javax.inject.Inject;
import br.gov.frameworkdemoiselle.annotation.NextView;
import br.gov.frameworkdemoiselle.annotation.PreviousView;
import br.gov.frameworkdemoiselle.stereotype.ViewController;
import br.gov.frameworkdemoiselle.template.AbstractListPageBean;
import br.gov.frameworkdemoiselle.transaction.Transactional;
import br.com.historia.historiacolaborativa.business.PromocaoBC;
import br.com.historia.historiacolaborativa.domain.Promocao;

@ViewController
@NextView("./promocao_edit.jsf")
@PreviousView("./promocao_list.jsf")
public class PromocaoListMB extends AbstractListPageBean<Promocao, Long> {

	private static final long serialVersionUID = 1L;

	@Inject
	private PromocaoBC promocaoBC;
	
	@Override
	protected List<Promocao> handleResultList() {
		return this.promocaoBC.findAll();
	}
	
	@Transactional
	public String deleteSelection() {
		boolean delete;
		for (Iterator<Long> iter = getSelection().keySet().iterator(); iter.hasNext();) {
			Long id = iter.next();
			delete = getSelection().get(id);
			if (delete) {
				promocaoBC.delete(id);
				iter.remove();
			}
		}
		return getPreviousView();
	}

}

src/main/java/br/com/historia/historiacolaborativa/view/TituloEditMB.java
package br.com.historia.historiacolaborativa.view;

import javax.inject.Inject;
import br.gov.frameworkdemoiselle.annotation.PreviousView;
import br.gov.frameworkdemoiselle.stereotype.ViewController;
import br.gov.frameworkdemoiselle.template.AbstractEditPageBean;
import br.gov.frameworkdemoiselle.transaction.Transactional;
import br.com.historia.historiacolaborativa.business.*;
import br.com.historia.historiacolaborativa.domain.*;
import javax.faces.model.*;
import org.primefaces.event.TransferEvent;
import org.primefaces.model.DualListModel;
import java.util.*;

// To remove unused imports press: Ctrl+Shift+o

@ViewController
@PreviousView("./titulo_list.jsf")
public class TituloEditMB extends AbstractEditPageBean<Titulo, Long> {

	private static final long serialVersionUID = 1L;

	@Inject
	private TituloBC tituloBC;
	

	
	@Override
	@Transactional
	public String delete() {
		this.tituloBC.delete(getId());
		return getPreviousView();
	}
	
	@Override
	@Transactional
	public String insert() {
		this.tituloBC.insert(this.getBean());
		return getPreviousView();
	}
	
	@Override
	@Transactional
	public String update() {
		this.tituloBC.update(this.getBean());
		return getPreviousView();
	}
	
	@Override
	protected Titulo handleLoad(Long id) {
		return this.tituloBC.load(id);
	}	
}

src/main/java/br/com/historia/historiacolaborativa/view/TituloListMB.java
package br.com.historia.historiacolaborativa.view;

import java.util.Iterator;
import java.util.List;
import javax.inject.Inject;
import br.gov.frameworkdemoiselle.annotation.NextView;
import br.gov.frameworkdemoiselle.annotation.PreviousView;
import br.gov.frameworkdemoiselle.stereotype.ViewController;
import br.gov.frameworkdemoiselle.template.AbstractListPageBean;
import br.gov.frameworkdemoiselle.transaction.Transactional;
import br.com.historia.historiacolaborativa.business.TituloBC;
import br.com.historia.historiacolaborativa.domain.Titulo;

@ViewController
@NextView("./titulo_edit.jsf")
@PreviousView("./titulo_list.jsf")
public class TituloListMB extends AbstractListPageBean<Titulo, Long> {

	private static final long serialVersionUID = 1L;

	@Inject
	private TituloBC tituloBC;
	
	@Override
	protected List<Titulo> handleResultList() {
		return this.tituloBC.findAll();
	}
	
	@Transactional
	public String deleteSelection() {
		boolean delete;
		for (Iterator<Long> iter = getSelection().keySet().iterator(); iter.hasNext();) {
			Long id = iter.next();
			delete = getSelection().get(id);
			if (delete) {
				tituloBC.delete(id);
				iter.remove();
			}
		}
		return getPreviousView();
	}

}

src/main/java/br/com/historia/historiacolaborativa/view/UsuarioListMB.java
package br.com.historia.historiacolaborativa.view;

import java.util.Iterator;
import java.util.List;
import javax.inject.Inject;
import br.gov.frameworkdemoiselle.annotation.NextView;
import br.gov.frameworkdemoiselle.annotation.PreviousView;
import br.gov.frameworkdemoiselle.stereotype.ViewController;
import br.gov.frameworkdemoiselle.template.AbstractListPageBean;
import br.gov.frameworkdemoiselle.transaction.Transactional;
import br.com.historia.historiacolaborativa.business.UsuarioBC;
import br.com.historia.historiacolaborativa.domain.Usuario;

@ViewController
@NextView("./usuario_edit.jsf")
@PreviousView("./usuario_list.jsf")
public class UsuarioListMB extends AbstractListPageBean<Usuario, Integer> {

	private static final long serialVersionUID = 1L;

	@Inject
	private UsuarioBC usuarioBC;
	
	@Override
	protected List<Usuario> handleResultList() {
		return this.usuarioBC.findAll();
	}
	
	@Transactional
	public String deleteSelection() {
		boolean delete;
		for (Iterator<Integer> iter = getSelection().keySet().iterator(); iter.hasNext();) {
			Integer id = iter.next();
			delete = getSelection().get(id);
			if (delete) {
				usuarioBC.delete(id);
				iter.remove();
			}
		}
		return getPreviousView();
	}

}

src/main/webapp/bookmark_edit.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui" xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets" template="/template/main.xhtml">

	<ui:define name="body">
		<h:form prependId="false">
			<p:toolbar>
				<p:toolbarGroup align="left">
					<p:commandButton value="#{messages['button.save']}" action="#{bookmarkEditMB.insert}"
						rendered="#{!bookmarkEditMB.updateMode}" ajax="false" />
					<p:commandButton value="#{messages['button.save']}" action="#{bookmarkEditMB.update}"
						rendered="#{bookmarkEditMB.updateMode}" ajax="false" />
					<p:commandButton value="#{messages['button.delete']}" onclick="confirmation.show()"
						rendered="#{bookmarkEditMB.updateMode}" type="button" immediate="true" ajax="false" />
					<p:confirmDialog message="#{messages['label.confirm.delete']}" showEffect="bounce" hideEffect="explode"
						header="#{messages['label.dialog.delete']}" severity="alert" widgetVar="confirmation">
						<h:commandButton value="#{messages['button.dialog.yes']}" action="#{bookmarkEditMB.delete}" immediate="true"
							ajax="false" />
						<h:commandButton value="#{messages['button.dialog.no']}" onclick="confirmation.hide()" type="button" />
					</p:confirmDialog>
				</p:toolbarGroup>
			</p:toolbar>

			<br />

			<p:fieldset legend="#{messages['bookmark.label']}" toggleable="true" toggleSpeed="500">
				<h:panelGrid id="fields" columns="3">
					<h:outputLabel value="#{messages['bookmark.label.id']}: " for="id" styleClass="text-input" />
					<h:outputText id="id" value="#{bookmarkEditMB.bean.id}" />
					<p:message for="id" />

					<h:outputLabel value="#{messages['bookmark.label.description']}: " for="description" styleClass="text-input" />
					<h:inputText id="description" value="#{bookmarkEditMB.bean.description}"
						title="#{messages['bookmark.alt.description']}" />
					<p:message for="description" />

					<h:outputLabel value="#{messages['bookmark.label.link']}: " for="link" styleClass="text-input" />
					<h:inputText id="link" value="#{bookmarkEditMB.bean.link}" title="#{messages['bookmark.alt.link']}" />
					<p:message for="link" />
				</h:panelGrid>
			</p:fieldset>
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/bookmark_list.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui" xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets" template="/template/main.xhtml">

	<ui:define name="body">
		<h:form>
			<p:toolbar>
				<p:toolbarGroup align="left">
					<p:commandButton title="#{messages['button.new']}" icon="ui-icon-document" action="#{bookmarkListMB.getNextView}"
						actionListener="#{bookmarkListMB.clear}" ajax="false" />

					<p:commandButton title="#{messages['button.delete']}" icon="ui-icon-trash" onclick="confirmation.show()"
						type="button" immediate="true" ajax="false" />

					<p:confirmDialog message="#{messages['label.confirm.delete']}" showEffect="bounce" hideEffect="explode"
						header="#{messages['label.dialog.alert']}!" severity="alert" widgetVar="confirmation">

						<h:commandButton value="#{messages['button.dialog.yes']}" action="#{bookmarkListMB.deleteSelection}"
							actionListener="#{bookmarkListMB.clear}" />
						<h:commandButton value="#{messages['button.dialog.no']}" onclick="confirmation.hide()" type="button" />
					</p:confirmDialog>
				</p:toolbarGroup>
			</p:toolbar>

			<p:dataTable id="list" var="bean" value="#{bookmarkListMB.resultList}">
				<f:facet name="header">#{messages['bookmark.list.table.title']}</f:facet>
				<p:column style="width:5%;">
					<h:selectBooleanCheckbox value="#{bookmarkListMB.selection[bean.id]}" />
				</p:column>
				<p:column style="width:5%;" sortBy="#{bean.id}">
					<f:facet name="header">#{messages['bookmark.label.id']}</f:facet>
					<h:outputText value="#{bean.id}" />
				</p:column>
				<p:column sortBy="#{bean.description}">
					<f:facet name="header">#{messages['bookmark.label.description']}</f:facet>
					<h:commandLink action="#{bookmarkListMB.getNextView}" actionListener="#{bookmarkListMB.clear}">
						<h:outputText value="#{bean.description}" />
						<f:param name="id" value="#{bean.id}" />
					</h:commandLink>
				</p:column>
				<p:column sortBy="#{bean.link}">
					<f:facet name="header">#{messages['bookmark.label.link']}</f:facet>
					<h:commandLink action="#{bookmarkListMB.getNextView}" actionListener="#{bookmarkListMB.clear}">
						<h:outputText value="#{bean.link}" />
						<f:param name="id" value="#{bean.id}" />
					</h:commandLink>
				</p:column>
			</p:dataTable>
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/estabelecimento_edit.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui" xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets" template="/template/main.xhtml">

	<ui:define name="body">
		<h:form prependId="false">
			<p:toolbar>
				<p:toolbarGroup align="left">
					<p:commandButton value="#{messages['button.save']}" action="#{estabelecimentoEditMB.insert}"
						rendered="#{!estabelecimentoEditMB.updateMode}" ajax="false" />
					<p:commandButton value="#{messages['button.save']}" action="#{estabelecimentoEditMB.update}"
						rendered="#{estabelecimentoEditMB.updateMode}" ajax="false" />
					<p:commandButton value="#{messages['button.delete']}" onclick="confirmation.show()"
						rendered="#{estabelecimentoEditMB.updateMode}" type="button" immediate="true" ajax="false" />
					<p:confirmDialog message="#{messages['label.confirm.delete']}" showEffect="bounce" hideEffect="explode"
						header="#{messages['label.dialog.delete']}" severity="alert" widgetVar="confirmation">
						<h:commandButton value="#{messages['button.dialog.yes']}" action="#{estabelecimentoEditMB.delete}" immediate="true"
							ajax="false" />
						<h:commandButton value="#{messages['button.dialog.no']}" onclick="confirmation.hide()" type="button" />
					</p:confirmDialog>
				</p:toolbarGroup>
			</p:toolbar>

			<br />

			<p:fieldset legend="#{messages['estabelecimento.label']}" toggleable="true" toggleSpeed="500">
				<h:panelGrid id="fieldsestabelecimento" columns="3">
				
					<h:outputLabel value="#{messages['estabelecimento.label.id_estabelecimento']}: " for="id_estabelecimento" styleClass="text-input" />
										
					<h:outputText id="id_estabelecimento" value="#{estabelecimentoEditMB.bean.id_estabelecimento}" />
					
					<p:message for="id_estabelecimento" />
						
					<h:outputLabel value="#{messages['estabelecimento.label.horario']}: " for="horario" styleClass="text-input" />
					
					<h:inputText id="horario" value="#{estabelecimentoEditMB.bean.horario}"
						title="#{messages['estabelecimento.alt.horario']}" />
					
					<p:message for="horario" />
						
					<h:outputLabel value="#{messages['estabelecimento.label.site']}: " for="site" styleClass="text-input" />
					
					<h:inputText id="site" value="#{estabelecimentoEditMB.bean.site}"
						title="#{messages['estabelecimento.alt.site']}" />
					
					<p:message for="site" />
						
					<h:outputLabel value="#{messages['estabelecimento.label.facebook']}: " for="facebook" styleClass="text-input" />
					
					<h:inputText id="facebook" value="#{estabelecimentoEditMB.bean.facebook}"
						title="#{messages['estabelecimento.alt.facebook']}" />
					
					<p:message for="facebook" />
						
					<h:outputLabel value="#{messages['estabelecimento.label.promocao']}: " for="promocao" styleClass="text-input" />
					
					<h:inputText id="promocao" value="#{estabelecimentoEditMB.bean.promocao}"
						title="#{messages['estabelecimento.alt.promocao']}" />
					
					<p:message for="promocao" />
						
				</h:panelGrid>
			</p:fieldset>
			
		</h:form>
	</ui:define>
</ui:composition>